Question 1

Write a Python program to convert an array to an ordinary list with the same items.

We can use the np.tolist() function.

In [12]:
import numpy as np
array = np.array([17, 9, 635])
lits = array.tolist()
print(f'List: {lits}')

List: [17, 9, 635]


In [13]:
array = np.array([[22,4,15,7], [65,12,7, 23]])
litt = array.tolist()
print(f'List: {litt}')

List: [[22, 4, 15, 7], [65, 12, 7, 23]]


2. Write a NumPy program to compute the sum of the diagonal elements of a given array.

   Hint: There are two possible methods to solve this problem: 

   Manually (without direct function). 
   Using the trace function

In [27]:
import numpy as np
              
# make array with numpy
new_array= np.arange(9).reshape(3,3)
print(new_array)              
# Manually summing up the diagonal elements
sum_of_diag = new_array[0,0] + new_array[1,1] + new_array[2,2]
print('Sum of diagonal = ',sum_of_diag)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Sum of diagonal =  12


In [31]:
import numpy as np
              
# make array with numpy
new_array= np.arange(9).reshape(3,3)
print(new_array)              
# applying new_array.trace() method
sum_of_diag = new_array.trace()
print('Sum of diagonal = ',sum_of_diag)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Sum of diagonal =  12


Question 3

Given an array of your choice, get all the values higher than X:

If a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 

In [43]:
import numpy as np

choice = [[1,2],[3,5]] 
new_choice = []
n_choice = np.array(choice)
for x in n_choice:
    for y in x:
        if y > 2:
            new_choice.append(y)
print(new_choice)

[3, 5]


Question 4

Given two arrays, A & B have the same shape. 

The task is to apply addition by hand: C is the new array. 

In [44]:
A = np.array([[2,3],[4,5]])
B = np.array([[6,2],[5,10]])
C = A + B
print(C)

[[ 8  5]
 [ 9 15]]


Question 5

Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function

In [3]:
import numpy as np
print("Original matrix:\n")
matrix1 = np.random.rand(3, 5)
print(matrix1)
print("\nSubtract the mean of each row of the said matrix:\n")
matrix_less_mean = matrix1 - matrix1.mean(axis=1, keepdims=True)
print(matrix_less_mean)

Original matrix:

[[0.65759617 0.11452958 0.6551558  0.64197512 0.10925494]
 [0.27258385 0.50261743 0.97087608 0.22585291 0.21930197]
 [0.27676971 0.42846271 0.11874966 0.93186492 0.10320122]]

Subtract the mean of each row of the said matrix:

[[ 0.22189385 -0.32117274  0.21945348  0.2062728  -0.32644739]
 [-0.1656626   0.06437098  0.53262963 -0.21239353 -0.21894448]
 [-0.09503993  0.05665306 -0.25305998  0.56005528 -0.26860842]]


Original matrix:

[[0.83185914 0.78186422]
 [0.98025577 0.73362703]]

Y matrix:

[[0.80686168]
 [0.8569414 ]]
[[ 0.02499746 -0.02499746]
 [ 0.12331437 -0.12331437]]
